'use server';

import { promises as fs } from 'fs';
import path from 'path';
// import { useEffect, useState} from 'react';

export default async function generateIdea() {
  try {
    // const [data, setData] = useState(null);

    // useEffect(() => {
    //  const fetchData = async () => {
    //    const res = await import('../public/data/ideas.json');
    //    setData(res.default);
    //  };
    //  fetchData();
    // }, []);

    // const filePath = path.resolve(process.cwd() + '.next', 'ideas.json');
    // const ideaFile = await fs.readFile(process.cwd() + '/.next/static', 'utf8');
    // const ideaData = JSON.parse(ideaFile);

    let randomNum: number = Rnbt(3, 1);

    switch (randomNum) {
      case 0:
        return `You are a 
                ${ideaData.verbs[Rnbt(ideaData.verbs.length, 1)]} 
                ${ideaData.beings[Rnbt(ideaData.beings.length, 1)]} 
                who must 
                ${ideaData.tasks[Rnbt(ideaData.tasks.length, 1)]}`
      case 1:
        return `A blend between the 
               ${ideaData.genres[Rnbt(ideaData.genres.length, 1)]} 
               and 
               ${ideaData.genres[Rnbt(ideaData.genres.length, 1)]} genres, 
               where you are a 
               ${ideaData.verbs[Rnbt(ideaData.verbs.length, 1)]} 
               ${ideaData.beings[Rnbt(ideaData.beings.length, 1)]}
               who will
               ${ideaData.tasks[Rnbt(ideaData.tasks.length, 1)]}.`
      //case 2: 
      //  return `A game about a 
      //         ${ideaData.objects[Rnbt(ideaData.objects.length, 1)]} 
      //         and a 
      //         ${ideaData.objects[Rnbt(ideaData.objects.length, 1)]}.`
      case 2: 
        return `You are a 
               ${ideaData.beings[Rnbt(ideaData.beings.length, 1)]} 
               who is ${ideaData.traits[Rnbt(ideaData.traits.length, 1)]}
               that tries to 
               ${ideaData.tasks[Rnbt(ideaData.tasks.length, 1)]}.`
      case 3: 
        return `A game where you must 
               ${ideaData.tasks[Rnbt(ideaData.tasks.length, 1)]} 
               with ${ideaData.objects[Rnbt(ideaData.objects.length, 1)]}
               in a mix between the 
               ${ideaData.genres[Rnbt(ideaData.tasks.length, 1)]} and
               ${ideaData.genres[Rnbt(ideaData.tasks.length, 1)]}.`
      default: return "Idea failed";
    }

    console.log(randomNum);
  } catch (error) {
    console.error(`Error parsing idea data:`, error);
    throw error;
  }
}

function Rnbt(max: number, min: number) {
  return Math.floor(Math.random() * ((max - min) + min));
}

let ideaData = {
  "beings": [
    "snowman", 
    "custodian", 
    "skeleton", 
    "fox", 
    "chicken", 
    "rabbit", 
    "snake", 
    "alien", 
    "business man",
    "druid",
    "android",
    "rogue",
    "cybernetic warrior",
    "space pirate",
    "necromancer",
    "shapeshifter",
    "swordsman",
    "alchemist",
    "bounty hunter",
    "alien",
    "dragon rider",
    "mech pilot",
    "hacker",
    "sorcerer",
    "time traveler",
    "mutant",
    "mercenary",
    "vampire",
    "knight",
    "elf archer",
    "assassin",
    "psionic",
    "robotic engineer",
    "intergalactic trader",
    "samurai",
    "demon hunter",
    "jedi",
    "shadow mage",
    "wizard",
    "space explorer",
    "ghost",
    "sniper",
    "gladiator",
    "enchanter",
    "cyborg",
    "ranger",
    "demon",
    "android medic",
    "paladin",
    "werewolf",
    "artificer",
    "ninja",
    "priest",
    "dark lord",
    "celestial being",
    "alien diplomat",
    "pirate captain",
    "healer",
    "elemental"
  ],
  "tasks": ["clean their room", 
    "defend a castle", 
    "do homework", 
    "find the treasure", 
    "build a tower",
    "find treasure",
    "defend a convoy",
    "explore alien ruins",
    "hack a mainframe",
    "escort a VIP",
    "hunt monsters",
    "solve a mystery",
    "rescue hostages",
    "gather resources",
    "craft weapons",
    "negotiate a truce",
    "raid a fortress",
    "investigate a crime scene",
    "survive a siege",
    "train a dragon",
    "steal enemy plans",
    "build a colony",
    "repair a starship",
    "rescue survivors",
    "uncover ancient secrets",
    "battle in an arena",
    "defuse a bomb",
    "capture a bounty",
    "forge alliances",
    "hunt an assassin",
    "spy on enemies",
    "infiltrate a base",
    "perform a ritual",
    "time travel to fix events",
    "gather intelligence",
    "protect a village",
    "retrieve a stolen artifact",
    "fight in a war",
    "terraform a planet",
    "win a gladiatorial contest",
    "sabotage enemy operations",
    "negotiate trade agreements",
    "rescue a prisoner",
    "retrieve lost technology",
    "clear a dungeon",
    "fight off an alien invasion",
    "conduct research",
    "lead a rebellion",
    "train a militia",
    "survive a harsh environment",
    "mediate peace between factions",
    "create new technology",
    "recover lost memories",
    "hunt down a rogue AI",
    "defend a castle",
    "sail a pirate ship",
    "throw pies at enemies",
    "ride a giant chicken into battle",
    "start a food fight in a tavern",
    "disguise yourself as a lamp post",
    "tickle a dragon",
    "compete in a snail race",
    "build a house out of cheese",
    "deliver pizza to aliens",
    "befriend a talking fish",
    "convince a goblin to dance",
    "prank call the enemy base",
    "juggle flaming swords",
    "convince NPCs you're a famous hero",
    "teach a robot to tell jokes",
    "join a synchronized swimming contest",
    "wrestle a bear in a tutu",
    "host an intergalactic karaoke night",
    "get lost in a hedge maze for days",
    "participate in a potato sack race with orcs",
    "accidentally become mayor of a town",
    "teach a troll proper table manners",
    "build a spaceship out of cardboard",
    "organize a flash mob in a fantasy city",
    "deliver an urgent message on roller skates",
    "convince an army of chickens to revolt",
    "chase a greased pig through a marketplace",
    "train a squirrel army",
    "make shadow puppets during a serious meeting",
    "sneak into a castle dressed as a janitor",
    "have a dance-off with a vampire",
    "convince a wizard their wand is actually a spoon",
    "argue with a sentient toaster",
    "participate in a pie-eating contest with giants",
    "challenge a cat to a staring contest",
    "build a trebuchet out of kitchen utensils",
    "host a tea party for monsters",
    "convince an ogre to go on a diet",
    "race on flying broomsticks while blindfolded",
    "try to teach a rock how to swim",
    "put on a puppet show for a group of trolls",
    "trick a dragon into thinking it's a puppy",
    "become a ghost and haunt random objects",
    "convince a pirate crew to switch to knitting",
    "organize a penguin parade",
    "steal candy from a baby monster",
    "hold a staring contest with a statue",
    "juggle flaming chickens",
    "convince a talking tree to start a podcast",
    "write a play about goblins and perform it",
    "give unsolicited fashion advice to a demon",
    "play hide and seek in an empty desert",
    "pretend to be a mannequin in a store window",
    "form a barbershop quartet with orcs",
    "start a conga line in the middle of a battle",
    "run a fake magic shop and prank customers",
    "convince a group of zombies to become vegan",
    "host an interspecies dating show",
    "play fetch with a werewolf",
    "hold an intergalactic stand-up comedy night",
    "paint fake windows on a dungeon wall",
    "challenge an elf to a knitting competition",
    "try to sell invisible potions to NPCs",
    "enter a potato into a beauty contest",
    "convince a spaceship AI to take up cooking",
    "start a rumor that dragons are allergic to gold",
    "hold a limbo contest with skeletons",
    "train a cat to walk on its hind legs",
    "hold an underwater basket weaving class",
    "convince a knight that their sword is cursed",
    "create a secret handshake with a goblin",
    "make a bed for a giant hamster",
    "start a bakery run by goblins",
    "convince NPCs you're a legendary sandwich artist",
    "organize a competitive cabbage rolling tournament",
    "steal a spaceship and rename it the 'Flying Banana'",
    "navigate a spaceship through an asteroid field",
    "deliver a message to a dragon in a hidden cave",
    "solve a murder mystery in a 1920s speakeasy",
    "collect magical herbs in an enchanted forest",
    "fix a time machine while avoiding paradoxes",
    "complete a farm simulation by growing unusual crops",
    "escape a zombie apocalypse using only household items",
    "mount a daring rescue mission on an alien planet",
    "organize a heist to steal a famous painting",
    "race against time to prevent a natural disaster",
    "join a guild of wizards to vanquish dark forces",
    "discover ancient artifacts while exploring ruins",
    "participate in a cooking competition with bizarre ingredients",
    "train a dragon to participate in aerial races",
    "uncover a conspiracy in a futuristic cyberpunk city",
    "create a sitcom about intergalactic roommates",
    "build a robot assistant using limited resources",
    "survive on a deserted island with only a survival kit",
    "track a legendary creature in a mysterious jungle",
    "initiate a trade agreement between warring factions",
    "assist a time traveler in completing a crucial task",
    "lead an expedition to find a lost city of gold",
    "compete in a dance-off against aliens",
    "explore the depths of the ocean in a submersible",
    "participate in a supernatural talent show",
    "bake the perfect cake in a high-stakes bakery championship",
    "unravel paranormal mysteries in a haunted mansion",
    "navigate political intrigue in a fantasy kingdom",
    "train a team of superheroes to protect the city",
    "construct a medieval castle with limited resources",
    "explore a post-apocalyptic wasteland for supplies",
    "defend your village from invading monsters",
    "search for a mythical artifact on a treasure hunt",
    "participate in a marathon with hilarious obstacles",
    "enter a dream world to solve puzzles and challenges",
    "solve riddles posed by a sphinx to proceed",
    "run a futuristic café serving mysterious dishes",
    "navigate a maze made entirely of candy",
    "join a guild of thieves in a high-stakes heist",
    "train for a global championship in a bizarre sport",
    "investigate paranormal activities in a small town",
    "construct a rollercoaster from scratch",
    "build a colony on a distant planet",
    "invest in a struggling business to turn a profit",
    "celebrate an intergalactic festival of lights",
    "defuse a bomb with only seconds left on the clock",
    "plan a wedding for a quirky couple",
    "tame wild beasts in a prehistoric environment",
    "launch a startup focused on magical technology",
    "thwart an evil sorcerer's plan to take over the world"
  ],
  "verbs": [
    "stinky",
    "spooky", 
    "cute",
    "fast",
    "strong",
    "brave",
    "mysterious",
    "funny",
    "dangerous",
    "bright",
    "ancient",
    "magical",
    "fearless",
    "powerful",
    "silent",
    "fierce",
    "clever",
    "loyal",
    "mighty",
    "invisible",
    "quick",
    "wise",
    "curious",
    "bold",
    "graceful",
    "agile",
    "energetic",
    "fearsome",
    "calm",
    "heroic",
    "playful",
    "cunning",
    "gentle",
    "fearful",
    "wild",
    "shiny",
    "unstoppable",
    "determined",
    "timid",
    "proud",
    "mysterious",
    "deadly",
    "legendary",
    "brilliant",
    "mischievous",
    "strange",
    "ruthless",
    "valiant",
    "daring",
    "patient",
    "intelligent",
    "massive",
    "elegant",
    "dark",
    "radiant",
    "fearless",
    "tough",
    "sly",
    "noble",
    "ancient",
    "witty",
    "swift",
    "vicious",
    "fragile",
    "bizarre",
    "magical",
    "sneaky",
    "warm",
    "cool",
    "dynamic",
    "quirky",
    "inventive",
    "brilliant",
    "fearsome",
    "devoted",
    "hilarious",
    "colorful",
    "puzzling",
    "enigmatic",
    "hungry",
    "intimidating",
    "mighty",
    "friendly",
    "devious",
    "adventurous",
    "creative",
    "restless",
    "trustworthy",
    "harsh",
    "bold",
    "fragile",
    "glowing",
    "eerie",
    "majestic",
    "vigilant",
    "ferocious",
    "slippery",
    "reckless",
    "tenacious",
    "ravenous",
    "helpful",
    "visionary",
    "eccentric",
    "stealthy",
    "whimsical",
    "stoic",
    "charming",
    "joyful",
    "unstable",
    "brutal",
    "gritty",
    "sinister",
    "honorable",
    "mellow",
    "bold"
  ],
  "genres": ["strategy",
    "survival", 
    "adventure", 
    "RPG", 
    "platformer", 
    "puzzle", 
    "idle game", 
    "base builder",
    "action",
    "adventure",
    "role-playing",
    "simulation",
    "strategy",
    "puzzle",
    "shooter",
    "platformer",
    "horror",
    "fighting",
    "racing",
    "sports",
    "massively multiplayer online (MMO)",
    "battle royale",
    "stealth",
    "hhythm",
    "survival",
    "visual novel",
    "card",
    "casual",
    "idle",
    "sandbox",
    "open world",
    "interactive fiction",
    "text-based",
    "educational",
    "tower defense",
    "metroidvania",
    "roguelike",
    "roguelite",
    "trivia",
    "management",
    "cooking",
    "fashion",
    "dating sim",
    "point-and-click",
    "escape room",
    "hack and slash",
    "tactical shooter",
    "bullet hell",
    "arena shooter",
    "simulation RPG",
    "crafting",
    "time management",
    "social deduction",
    "strategy RPG",
    "card battle",
    "resource management"
  ],
  "objects": [
    "umbrella",
    "cup o' noodles", 
    "chair", 
    "penguin", 
    "sword", 
    "book",
    "laser sword",
    "magic wand",
    "space ship",
    "mystical amulet",
    "smartphone",
    "dragon egg",
    "hoverboard",
    "potion bottle",
    "time machine",
    "crystal ball",
    "robot companion",
    "fantasy map",
    "alien artifact",
    "potion ingredients",
    "book of spells",
    "spacesuit",
    "cloak of invisibility",
    "VR headset",
    "treasure chest",
    "teleportation device",
    "grimoire",
    "holographic projector",
    "enchanted mirror",
    "infinity gauntlet",
    "doppelganger mask",
    "biometric scanner",
    "ancient scroll",
    "mech suit",
    "fairy dust",
    "medieval shield",
    "sonic screwdriver",
    "quill pen",
    "elven bow",
    "alien communicator",
    "astral compass",
    "time crystal",
    "magical staff",
    "biopod",
    "mystery box",
    "golem clay",
    "nanochips",
    "crystal shard",
    "phoenix feather",
    "wishing well",
    "hover car",
    "celestial sphere",
    "magic mirror",
    "charm bracelet",
    "star map",
    "genie lamp",
    "memory crystal",
    "farm tractor",
    "hiking backpack",
    "fish rod",
    "camping tent",
    "wireless speaker",
    "coffee mug",
    "laptop",
    "fire pit",
    "sports gear",
    "board game",
    "camping stove",
    "puzzle cube",
    "keyboard",
    "wardrobe",
    "gardening tools",
    "bicycle",
    "cooking pot",
    "canvas painting",
    "catapult",
    "magic gemstone",
    "scepter",
    "space helmet",
    "zip line",
    "miniature garden",
    "falconry glove",
    "water bottle",
    "blueprints",
    "broomstick",
    "futuristic weapon",
    "telescope",
    "pet rock",
    "flashlight",
    "sun glasses",
    "sandwich maker",
    "stickers book",
    "fire extinguisher",
    "stethoscope",
    "camping cooler",
    "pocket watch",
    "guitar",
    "drawing tablet",
    "snowboard",
    "portable charger",
    "ice skates",
    "first aid kit",
    "cooking knife",
    "laptop stand",
    "art supplies",
    "drone",
    "medieval armor",
    "space station",
    "crystal cave",
    "chalice",
    "energy shield",
    "spinning top",
    "bubble wand",
    "gnome statue",
    "sled",
    "fantasy creature plush",
    "potion cauldron",
    "futuristic timepiece",
    "sun dial",
    "vortex manipulator",
    "fencing sword",
    "weather vane",
    "firework kit",
    "nature journal",
    "balloon",
    "backpack",
    "lantern",
    "sculpting clay",
    "fairy tale book",
    "slingshot",
    "horse saddle",
    "chalkboard",
    "bluetooth earbuds",
    "infinity book",
    "plague doctor mask",
    "potion of healing",
    "wind-up toy",
    "clock tower",
    "record player",
    "tarot cards",
    "futuristic vehicle",
    "bionic limb",
    "time capsule",
    "fantasy castle model",
    "kite",
    "essences flask",
    "ritual altar",
    "space-time diagram",
    "marbles",
    "night vision goggles",
    "dragon figurine",
    "potion of strength",
    "gemstone necklace",
    "antique clock",
    "climbing gear",
    "radios",
    "chess set",
    "nerf blaster",
    "antigravity belt",
    "potion of wisdom",
    "jigsaw puzzle",
    "mysterious key",
    "frisbee",
    "portable telescope",
    "meteorite fragment",
    "mystic tome",
    "gem cutter",
    "collectible card",
    "fishing net",
    "mood ring",
    "magic compass",
    "wooden staff",
    "potion of agility",
    "retrofuturistic typewriter",
    "monocle",
    "space dock",
    "wand of fire",
    "cosmic map",
    "seeds pouch",
    "mandala coloring book",
    "goblet of fire",
    "fishing lure",
    "bioluminescent algae",
    "ominous skull",
    "crystal prism",
    "breezeway",
    "gadget box",
    "space elevator",
    "karaoke machine",
    "origami paper",
    "hammer of dwarves",
    "eco-friendly tote",
    "magic feather",
    "painting easel",
    "fire-breathing dragon",
    "wireless mouse",
    "hiking boots",
    "ritual dagger",
    "gold coins",
    "fantasy animal figurine",
    "neon sign",
    "campfire stories collection"
  ],
  "traits": [
    "afraid of heights", 
    "overly confident", 
    "allways hungry", 
    "very happy",
    "fiercely loyal",
    "a perfectionist",
    "socially awkward",
    "extremely curious",
    "easily distracted",
    "a night owl",
    "chronically late",
    "a diligent worker",
    "highly motivated",
    "perpetually optimistic",
    "easily offended",
    "a procrastinator",
    "very empathetic",
    "often sarcastic",
    "a natural leader",
    "constantly daydreaming",
    "a rule follower",
    "a thrill-seeker",
    "hopelessly romantic",
    "introverted",
    "highly analytical",
    "a bit of a neat freak",
    "a good listener",
    "a risk-taker",
    "rather forgetful",
    "very stubborn",
    "quick-tempered",
    "a peacemaker",
    "extremely creative",
    "an adventure lover",
    "often pessimistic",
    "detail-oriented",
    "very generous",
    "fiercely independent",
    "easily influenced",
    "very talkative",
    "a bit of a prankster",
    "a workaholic",
    "very patient",
    "self-critical",
    "easily bored",
    "very methodical",
    "a people pleaser",
    "easily motivated",
    "very competitive",
    "generally laid-back",
    "often anxious",
    "a daydreamer"
  ]
}
